### ISSUE TITLE
Art from Shadowbringers?

### ISSUE THREAD

**Issue by ValiantBlade** [RZetko/galaxy-integration-ffxiv#2]
Why does this integration use art from the original FFXIV instead of the newer art from the Shadowbringers page on Square's site?

It seems weird to use art from past versions of an MMO, using the newest art just makes more sense to me. Square Enix's store page has a format not too different from the actual game pages in GOG Galaxy.

**Comment by RZetko** [comment]
That's good idea. I used it because of 2 reasons:

- I initially used FF XIV: Realm Reborn because it was first in the list in GOG client 😄 
- I wanted to use old FF XIV entry because users might only have basic license without any expansions. Shadowbringers is tough really more prominent now and way more recognizable that old art.

Thank you for bringing this up. I'll update it later in the evening today and then close this issue.

**Comment by ValiantBlade** [comment]
I mean, I have absolutely no idea if this is possible but maybe it could be an option to change which game is shown based on if the expansion's files are there? Maybe if no expansions are detected, Realm Reborn, but like if a file from each expac is present then it would change the art?

**Comment by RZetko** [comment]
Yeah, that would be perfect case and that's what I also wanted. There are multiple problems though:

- XIVAPI/Lodestone which I use to fetch info about user account/character doesn't support getting list of licenses/expansions for that account. I can find out list of expansions only after the game is installed, which would mean I'd have to switch cover art after game is installed.
- I'm not sure if I can actually affect which game is recognized in client. It's entirely possible that even if I change name in my integration, it'll still be showing original FF XIV art and info because that's what GOG backend returns when detecting game.

Do you by any chance get this cover art when importing FF XIV into your GOG client? (https://images.gog.com/1c9bd9d67a6297f62810fee36e5b767db9cfadb2173a68a4476142c9c3b94005.jpg?namespace=gamesdb)

I'll take a look at it and see what I can do.

**Comment by RZetko** [comment]
I noticed that final_fintasy_xiv_shadowbringers has been added to GOG's games backend. Unfortunately it still pulls info about realm reborn instead of shadowbringers but that's still a lot better than old art and irrelevant game info. I update game name and here's what we got alongside with it:

- it's now showing more appropriate cover art and game info (Final Fantasy: A Realm Reborn)
- it's now showing users activity (how many hours have they played, how many hours have they reached) from other platforms (steam)

Download version 1.1.1 and it should show a lot better in your library.

Thanks for filling this issue and helping me make this integration better.
